os: linux

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

install:
  - true

notifications:
  email: false

cache:
  directories:
    - $GOPATH/pkg/mod
    - /home/travis/.cache/go-build

script:
  - cd bytesbuilder && go test -v -race && cd ..
  - cd ecdsa && go test -v -race